/*============================================================================*\
*
* Copyright Karol Domanski, All Rights Reserved
* It is not allowed to reproduce or utilize parts of this document in any form
* or by any means, including photocopying and microfilm, without permission in
* written by Karol Domanski.
*
\*============================================================================*/

#pragma once

/*****************************************************************************
                       PUBLIC DEFINES / MACROS / ENUMS
*****************************************************************************/

#define TERMINAL_BAUDRATE 57600

#define START_MODULE_TIME_TO_STARTUP_MILLIS 100U

#define MAXIMUM_TIME_WITHOUT_MOVEMENT_MILLIS 25000U

#define BATTERY_LOW_BATTERY_LEVEL_VOLT 12.0F
#define BATTERY_CRITICAL_LOW_BATTERY_LEVEL_VOLT 10.5F
#define BATTERY_AVG_NBR_OF_SAMPLES 20U

#define LINE_SENSOR_FRONT_LEFT_ENABLE true
#define LINE_SENSOR_FRONT_RIGHT_ENABLE true
#define LINE_SENSOR_BACK_LEFT_ENABLE false
#define LINE_SENSOR_BACK_RIGHT_ENABLE false

#define DISTANCE_SENSOR_LEFT_ENABLE true
#define DISTANCE_SENSOR_LEFT_DIAG_ENABLE true
#define DISTANCE_SENSOR_FRONT_ENABLE true
#define DISTANCE_SENSOR_RIGHT_DIAG_ENABLE true
#define DISTANCE_SENSOR_RIGHT_ENABLE true
#define DISTANCE_SENSOR_BACK_ENABLE true

#define DISTANCE_SENSOR_LEFT_WEIGHT 5
#define DISTANCE_SENSOR_LEFT_DIAG_WEIGHT 2
#define DISTANCE_SENSOR_FRONT_WEIGHT 0
#define DISTANCE_SENSOR_RIGHT_DIAG_WEIGHT -2
#define DISTANCE_SENSOR_RIGHT_WEIGHT -5

#define TACTIC_SPEED_AFTER_ROTATATION 255

#define TACTIC_ROTATE_AND_GO_CCW_ROTATING_TIME_MILLIS 165U
#define TACTIC_ROTATE_AND_GO_CW_ROTATING_TIME_MILLIS 225U
#define TACTIC_ROTATE_AND_WAIT_ROTATING_TIME_MILLIS 240U
#define TACTIC_ROTATING_SPEED 200
#define TACTIC_ROTATING_AND_GO_SPEED 255
#define TACTIC_ROTATE_AND_WAIT_SPEED 200
#define TACTIC_ROTATE_AND_GO_ROTATING_TIME_MILLIS 200

#define FIGHT_PID_KP_VALUE 50
#define FIGHT_PID_KI_VALUE 0
#define FIGHT_PID_KD_VALUE 0
#define FIGHT_PID_INTEGRAL_WINDUP 300
#define FIGHT_PID_OUTPUT_MAX 255
#define FIGHT_PID_OUTPUT_MIN -255

#define FIGHT_MOTOR_DEFAULT_SPEED 70
#define FIGHT_MAX_ATTACK_SPEED 255
#define EDGE_REVERSAL_SPEED_FROM_LINE -150
#define EDGE_ROTATE_AFTER_REVERSAL_SPEED 200
#define FIGHT_USING_LAST_COURSE_EXECUTION_TIME_MILLIS 3000

#define FIGHT_FRONT_TARGETTING_TIMEOUT_MILLIS 500

#define EDGE_ESTIMATING_LINE_ANGLE_DELAY_MILLIS 70U
#define EDGE_REVERSE_TIME_MILLIS 150U
#define EDGE_FRONT_LEFT_RIGHT_ROTATE_DURATION_MILLIS 225
#define EDGE_FRONT_LEFT_ROTATE_DURATION_MILLIS 250
#define EDGE_FRONT_RIGHT_ROTATE_DURATION_MILLIS 130

#define BACK_HALF_TURN_DURATION_TIME_MILLIS 300U
#define BACK_SENSOR_BACK_ACTIVITY_TIME_MILLIS 300U
#define BACK_HALF_TURN_ROTATE_SPEED 200

#define MOTOR_STOP_SPEED 0